[Distribution]
Distribution=postmarketos
Release=edge
Architecture=arm

[Output]
Format=cpio
Output=minitrd
CompressOutput=gz
CompressLevel=9
ManifestFormat=
SplitArtifacts=

[Content]
Bootable=no
MakeInitrd=no
Packages=busybox
WithDocs=no
CleanPackageMetadata=yes
RemoveFiles=
        /boot
        /etc/apk
        /lib/apk
        /usr/include
        /usr/share/apk
        /usr/share/doc
        /usr/share/man
        /usr/share/misc
        /usr/share/zoneinfo
        /var/cache
        /var/lib/apk
        /var/log
